[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://ecommerce-backend-ygbi.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200