services:
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: render-jwt-secret-2024-super-secure
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString

  - type: web
    name: ecommerce-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ecommerce-backend.onrender.com

databases:
  - name: ecommerce-db
    plan: free
    databaseName: ecommerce_db