version: '3.8'

services:
  backend:
    build: ../backend
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend